const GENRES = [
    {value: " ", label: "All"},
    {value: "Action", label: "Action"},
    {value: "Adventure", label: "Adventure"},
    {value: "Animation", label: "Animation"},
    {value: "Biography", label: "Biography"},
    {value: "Comedy", label: "Comedy"},
    {value: "Crime", label: "Crime"},
    {value: "Documentary", label: "Documentary"},
    {value: "Drama", label: "Drama"},
    {value: "Family", label: "Family"},
    {value: "Fantasy", label: "Fantasy"},
    {value: "Film-Noir", label: "Film-Noir"},
    {value: "Game-Show", label: "Game-Show"},
    {value: "History", label: "History"},
    {value: "Horror", label: "Horror"},
    {value: "Music", label: "Music"},
    {value: "Musical", label: "Musical"},
    {value: "Mystery", label: "Mystery"},
    {value: "News", label: "News"},
    {value: "Reality-TV", label: "Reality-TV"},
    {value: "Romance", label: "Romance"},
    {value: "Sci-FI", label: "Sci-FI"},
    {value: "Sport", label: "Sport"},
    {value: "Talk-Show", label: "Talk-Show"},
    {value: "Thriller", label: "Thriller"},
    {value: "War", label: "War"},
    {value: "Western", label: "Western"}
]
export default GENRES